### ISSUE TITLE
Can't build with 1.6

### ISSUE THREAD

**Issue by nitay** [facebook/facebook-oss-pom#6]
Setting <project.build.targetJdk>1.6</project.build.targetJdk> doesn't work for me:

[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] bootstrap class path not set in conjunction with -source 1.6
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.913s
[INFO] Finished at: Thu Jun 27 00:36:25 EDT 2013
[INFO] Final Memory: 14M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project hadoop-jobs: Compilation failure
[ERROR] warnings found and -Werror specified
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

I tried also copying the entire <plugin> section for the compiler and removing the Werror but that didn't work either. Any ideas? @hgschmie
